# Generated by Django 2.2.7 on 2020-02-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200207_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='actioned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
