# Generated by Django 2.2.7 on 2019-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
