# Generated by Django 2.2.7 on 2019-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20191119_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
