# Generated by Django 2.2.7 on 2019-11-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20191119_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
