# Generated by Django 2.2.7 on 2019-11-19 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
