# Generated by Django 2.2.7 on 2019-11-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='position',
            field=models.IntegerField(unique=True),
        ),
    ]
