# Generated by Django 2.2.7 on 2019-11-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20191128_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='links.Collection'),
        ),
    ]
