# Generated by Django 2.2.7 on 2019-11-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20191128_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('collection', 'position')},
        ),
    ]
