# Generated by Django 2.2.7 on 2019-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20191128_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
