# Generated by Django 2.2.7 on 2019-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20191128_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='column',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='collection',
            name='position',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='collection',
            name='position_temp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='position',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
