# Generated by Django 2.2.7 on 2019-11-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_auto_20191129_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='column',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
