# Generated by Django 2.2.7 on 2019-11-29 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0009_auto_20191129_0957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('position', 'column', 'user')},
        ),
    ]
