# Generated by Django 2.2.7 on 2019-12-02 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_collection_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='num_of_columns',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
