# Generated by Django 2.2.7 on 2019-12-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_page_num_of_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='column_order_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='column_order_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='column_order_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='column_order_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
