# Generated by Django 2.2.7 on 2019-12-03 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0016_auto_20191203_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'user'), ('position', 'column', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
    ]
