# Generated by Django 2.2.7 on 2019-12-05 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0018_auto_20191203_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('position', 'name', 'user'), ('name', 'user')},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='column',
        ),
    ]
