# Generated by Django 2.2.7 on 2019-12-09 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0019_auto_20191205_0816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('position', 'name', 'user'), ('name', 'user', 'page')},
        ),
    ]
