# Generated by Django 2.2.7 on 2019-12-09 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0020_auto_20191209_1219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'user', 'page'), ('position', 'name', 'page', 'user')},
        ),
    ]
