# Generated by Django 2.2.7 on 2019-12-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0021_auto_20191209_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='position_temp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
