# Generated by Django 2.2.7 on 2020-01-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0022_page_position_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='position',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
