# Generated by Django 2.2.7 on 2020-01-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0023_auto_20200103_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_collection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='links.Collection')),
                ('dest_page', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='links.Page')),
            ],
        ),
    ]
