# Generated by Django 2.2.7 on 2020-01-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0026_auto_20200109_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='num_of_columns',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4),
        ),
    ]
