# Generated by Django 2.2.7 on 2020-01-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0028_auto_20200110_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='public',
        ),
        migrations.AddField(
            model_name='collection',
            name='display_mode',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
