# Generated by Django 2.2.7 on 2020-01-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0029_auto_20200113_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
