# Generated by Django 2.2.7 on 2020-01-14 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0030_collection_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='display_mode',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
