# Generated by Django 2.2.7 on 2020-01-14 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0032_auto_20200114_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
