# Generated by Django 2.2.7 on 2020-01-23 11:27

from django.db import migrations, models
import links.models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0033_auto_20200114_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=links.models.icon_location),
        ),
    ]
