# Generated by Django 2.2.7 on 2019-11-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
