# Generated by Django 2.2.7 on 2019-11-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_auto_20191121_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpurchase',
            name='payment_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
