# Generated by Django 2.2.7 on 2019-11-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_premiumpurchase_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpurchase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='premiumpurchase',
            name='county',
        ),
        migrations.RemoveField(
            model_name='premiumpurchase',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='premiumpurchase',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='premiumpurchase',
            name='town_city',
        ),
    ]
